-- SQL Script to Create and Populate Perk Notifications Table

-- 1. Create the new table 'perk_notifications'
-- This table will store the base messages and the tiered reminder schedules for each perk.
-- It is linked to the 'perk_definitions' table via the 'perk_id' foreign key.
-- We use JSONB for the reminder_schedule column as it's an efficient way to store and query JSON data in PostgreSQL.

CREATE TABLE public.perk_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  perk_id UUID NOT NULL REFERENCES public.perk_definitions(id) ON DELETE CASCADE,
  base_message TEXT,
  reminder_schedule JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add a comment to the table for clarity
COMMENT ON TABLE public.perk_notifications IS 'Stores tiered push notification messages for credit card perks.';

-- Optional but recommended: Create a trigger to automatically update the 'updated_at' timestamp on any row change.
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON public.perk_notifications
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


-- 2. Insert the notification data into the new table
-- Each INSERT statement corresponds to a perk from our generated JSON file.
-- Note: Single quotes within the text are escaped by doubling them (e.g., 'it's' becomes 'it''s').

INSERT INTO public.perk_notifications (perk_id, base_message, reminder_schedule) VALUES
('008f140c-56fe-48f1-9e89-6c39391e3def', 'Your Saks credit is here for your next glow up! ✨ Spoil yourself with something stylish before it''s gone.', '{"30": {"title": "Your Saks Credit Expires This Month!", "time_modifier": "There''s still a month to use your {{amount}} credit. It''s giving main character energy."}, "14": {"title": "Don''t Sleep on Your Saks Credit", "time_modifier": "Only two weeks left to claim your {{amount}} credit. Pro-tip: grab a gift card in-store so you don''t lose it!"}}'),
('0faeed05-234e-4110-a710-b8cb41bb0f72', 'Your next adventure is calling! 🗺️ Use your Capital One Travel Credit before it says ''bon voyage!''', '{"60": {"title": "Catch Flights, Not Feelings!", "time_modifier": "You have two months to use your {{amount}} travel credit. Where to next?"}, "30": {"title": "Your Travel Credit Expires This Month!", "time_modifier": "Don''t let your {{amount}} travel credit fly away! Book that trip this month."}}'),
('1aab4bed-a106-47a2-a7e5-0ae17b1fde02', 'Your monthly Dunkin'' credit is here to make your day sweeter. You literally can''t say no. 🍩', '{"7": {"title": "Your Monthly Dunkin'' Run Awaits", "time_modifier": "You have one week left to use your {{amount}} at Dunkin''."}, "3": {"title": "Spill the Tea (with your Dunkin'' Credit!)", "time_modifier": "Only 3 days left to grab a coffee or a treat on us!"}, "1": {"title": "🚨 LAST DAY for your Dunkin'' Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit. Don''t leave money on the table!"}}'),
('207067ca-6933-40cf-ab7b-1d2d36bf067f', 'Your Uber Cash is giving... free ride or boba run! 🧋 Don''t let this perk ghost you.', '{"7": {"title": "Your Monthly Uber Cash is Expiring", "time_modifier": "You have one week left to use your {{amount}} in Uber Cash. It''s giving main character energy. ✨"}, "3": {"title": "Don''t Forget Your Uber Credit!", "time_modifier": "Only 3 days left for a ride or a tea! Where to? 🚗"}, "1": {"title": "🚨 LAST DAY for Uber Cash", "time_modifier": "Today is your final chance to use your {{amount}} in Uber Cash. It''s now or never!"}}'),
('32a15587-31ef-473a-a73b-b40c68026419', 'It''s giving... staycation! 🏨 Your Hotel Credit is waiting to be used on a cozy stay.', '{"60": {"title": "Time to Plan Your Next Getaway!", "time_modifier": "You have two months to use your {{amount}} hotel credit. Book your escape now! 😴"}, "30": {"title": "Your Hotel Credit Expires This Month!", "time_modifier": "Don''t miss out on a discounted stay. Use your {{amount}} credit this month!"}}'),
('360e8050-d55d-46e4-a604-a3006dc39724', 'Ready for some gains? 💪 Your Equinox Credit is about to expire. Hit the gym and go beast mode!', '{"7": {"title": "Your Monthly Equinox Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Equinox credit."}, "3": {"title": "Don''t Forget Your Equinox Credit!", "time_modifier": "Only 3 days left to get a workout in! 🏋️‍♀️"}, "1": {"title": "🚨 LAST DAY for your Equinox Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('37eeb419-2110-4ca2-ac70-0eebbd587530', 'Living your best life just got easier. ✨ Your Hotel Credit for Fine Hotels + Resorts is waiting for you to book a boujee escape!', '{"60": {"title": "Time to Plan a Luxurious Escape!", "time_modifier": "You have two months to use your {{amount}} FHR/THC credit. 🍾"}, "30": {"title": "Your Hotel Credit Expires This Month!", "time_modifier": "Don''t miss out on luxury! Use your {{amount}} credit this month."}}'),
('38ca9405-eafc-4f95-aac0-c436d050c0d0', 'Boba run? Snack attack? 🧋 Your DoorDash credit for non-restaurant goodies is expiring. Don''t fumble the bag!', '{"7": {"title": "Your Monthly DoorDash Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} DoorDash credit for basically anything."}, "3": {"title": "Don''t Forget Your DoorDash Credit!", "time_modifier": "Only 3 days left to stock up on snacks or essentials! 🛒"}, "1": {"title": "🚨 LAST DAY for your DoorDash Credit", "time_modifier": "This is not a drill! Use your {{amount}} credit today or lose it!"}}'),
('55fec7a1-de50-40c9-b5a2-0f456161def0', 'What are we binge-watching? 🎬 Your Disney Bundle credit is about to expire. Don''t miss out!', '{"7": {"title": "Your Monthly Streaming Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Disney Bundle credit."}, "3": {"title": "Don''t Forget Your Disney Bundle Credit!", "time_modifier": "Only 3 days left for a movie marathon! 📺"}, "1": {"title": "🚨 LAST DAY for your Disney Bundle Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('66ca3bae-2feb-40ee-b907-b07c845163fd', 'Slay your workout! 🚴‍♀️ Your Peloton Membership Credit is expiring. Clip in and feel the burn!', '{"7": {"title": "Your Monthly Peloton Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Peloton credit."}, "3": {"title": "Don''t Forget Your Peloton Credit!", "time_modifier": "Only 3 days left to ride! 🔥"}, "1": {"title": "🚨 LAST DAY for your Peloton Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('7829f4fe-8428-492e-948c-746d474fa7f5', 'IYKYK... airport lines are not the vibe. ✈️ Your CLEAR Plus Credit is expiring, so renew now and breeze through security!', '{"60": {"title": "Time to Renew Your CLEAR Membership!", "time_modifier": "You have two months to use your {{amount}} CLEAR credit."}, "30": {"title": "Your CLEAR Credit Expires This Month!", "time_modifier": "Don''t get stuck in line! Use your {{amount}} credit this month. 😎"}}'),
('7bd0e404-3ca4-409f-9827-a78d4f51584f', 'Vacay mode: activated! ☀️ Your Hilton Resort Credit is ready for you. Book that poolside cabana!', '{"30": {"title": "Your Hilton Resort Credit Expires This Month!", "time_modifier": "There''s still a month to use your {{amount}} credit on a relaxing stay. 🍹"}, "14": {"title": "Time is Running Out on Your Hilton Credit", "time_modifier": "Only two weeks left to claim your {{amount}} credit."}}'),
('7d82e0d9-4495-4ac4-86f8-f819b0762747', 'Time to make a new core memory. 🏡 Your Delta Stays Credit is expiring. Book your perfect home away from home!', '{"60": {"title": "Time to Plan Your Next Vacation!", "time_modifier": "You have two months to use your {{amount}} Delta Stays credit."}, "30": {"title": "Your Delta Stays Credit Expires This Month!", "time_modifier": "Don''t miss out! Use your {{amount}} credit on a great stay. ✈️"}}'),
('7d9d198c-5fd4-4d3e-b095-8059e89273d2', 'This is your sign to fly through security like a VIP! ✨ Your CLEAR Plus Credit is waiting.', '{"60": {"title": "Time to Renew Your CLEAR Membership!", "time_modifier": "You have two months to use your {{amount}} CLEAR credit."}, "30": {"title": "Your CLEAR Credit Expires This Month!", "time_modifier": "Keep the VIP treatment! Use your {{amount}} credit this month. 🚀"}}'),
('7e10ad1b-792e-4c34-8d36-bd0ebbca8591', 'Stop doomscrolling and start streaming! 🍿 Your Digital Entertainment Credit is here. What are you watching?', '{"7": {"title": "Your Monthly Entertainment Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} entertainment credit."}, "3": {"title": "Don''t Forget Your Entertainment Credit!", "time_modifier": "Only 3 days left to stream! 🎧"}, "1": {"title": "🚨 LAST DAY for your Entertainment Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('8250b448-86d1-49c1-b37d-40c0039a5a0c', 'It''s giving... concert season! 🎤 Your StubHub credit is your ticket to fun. Get those tix before they''re gone!', '{"30": {"title": "Your Event Credit Expires This Month!", "time_modifier": "There''s still a month to use your {{amount}} credit on StubHub or viagogo. 🎟️"}, "14": {"title": "Time is Running Out on Your Event Credit", "time_modifier": "Only two weeks left to claim your {{amount}} credit."}}'),
('86836d3c-6573-43ec-9b42-33493bec5765', 'Fueling your boba cravings or a late-night snack run. 🚕 Your Uber Cash is about to vanish. Use it before it''s gone!', '{"7": {"title": "Your Monthly Uber Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} in Uber Cash."}, "3": {"title": "Don''t Forget Your Uber Credit!", "time_modifier": "Only 3 days left! 🍕"}, "1": {"title": "🚨 LAST DAY for Uber Cash", "time_modifier": "Today is your final chance to use your {{amount}} in Uber Cash!"}}'),
('8726f459-c527-45c6-8321-59666524784e', 'Sushi, tacos, or boba? 🍽️ Your DoorDash restaurant credit is getting cold. Order something delicious tonight!', '{"7": {"title": "Your Monthly Food Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} DoorDash credit."}, "3": {"title": "Don''t Forget Your DoorDash Credit!", "time_modifier": "Only 3 days left to get a tasty meal! 🥡"}, "1": {"title": "🚨 LAST DAY for your DoorDash Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('8c57ee72-0b5b-4d93-aeee-150c15539514', 'Are you hangry? 🤔 Your monthly Grubhub credit is ready to treat you. Don''t let it go to waste!', '{"7": {"title": "Your Monthly Grubhub Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Grubhub credit."}, "3": {"title": "Don''t Forget Your Grubhub Credit!", "time_modifier": "Only 3 days left to order in! 🍝"}, "1": {"title": "🚨 LAST DAY for your Grubhub Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('90ec407b-6efc-4b7a-b071-3aa51e68af2c', 'Need a lift? 🚗 Your rideshare credit is expiring soon. Get where you need to go, on us!', '{"7": {"title": "Your Monthly Ride Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} rideshare credit."}, "3": {"title": "Don''t Forget Your Rideshare Credit!", "time_modifier": "Only 3 days left to catch a ride! 🗺️"}, "1": {"title": "🚨 LAST DAY for your Rideshare Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('a2e8f7d1-5b7a-4b0e-8b1a-9f8d7c6b5a4d', 'It''s giving... free boujee hotel stay! 🏝️ Your Annual Free Night Award at a Marriott Bonvoy hotel is here.', '{"60": {"title": "Time to Plan Your Free Getaway!", "time_modifier": "You have two months to use your Free Night Award. ✨"}, "30": {"title": "Your Free Night Award Expires This Month!", "time_modifier": "Don''t miss out on a free night! Book your stay this month."}}'),
('a30da18a-b7f8-4d52-bb8a-80200f62e2b5', 'Grocery run! 🛒 Your DoorDash credit for essentials is about to expire. Time for a snack haul!', '{"7": {"title": "Your Monthly Grocery Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} DoorDash credit."}, "3": {"title": "Don''t Forget Your DoorDash Credit!", "time_modifier": "Only 3 days left to get your groceries! 🥑"}, "1": {"title": "🚨 LAST DAY for your DoorDash Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('ae2ab1a1-3aad-4377-97eb-542ea733d905', 'A table for you, perhaps? 🍷 Your credit for Exclusive Tables on OpenTable is waiting. It''s chef''s kiss! 👌', '{"30": {"title": "Your Dining Credit Expires This Month!", "time_modifier": "There''s still a month to use your {{amount}} credit for an exclusive meal. 🍴"}, "14": {"title": "Time is Running Out on Your Dining Credit", "time_modifier": "Only two weeks left to claim your {{amount}} credit."}}'),
('b4ca65e4-a537-4688-b46a-63326bd72f36', 'Free shipping AND free shows? Say less. ✅ Your Walmart+ membership credit (which includes Paramount+!) is ready.', '{"7": {"title": "Your Monthly Walmart+ Perk is Expiring", "time_modifier": "You have one week left to claim your Walmart+ credit."}, "3": {"title": "Don''t Forget Your Walmart+ Credit!", "time_modifier": "Only 3 days left for free shipping and more! 📦"}, "1": {"title": "🚨 LAST DAY for your Walmart+ Credit", "time_modifier": "Today is your final chance to get your membership rebate!"}}'),
('be07d25c-2f76-4a09-8bfd-78c3c047163b', 'Press play on free entertainment! 🎵 Your Apple TV+ and Apple Music subscriptions are waiting. What''s on your playlist?', '{"60": {"title": "Time to Activate Your Apple Perks!", "time_modifier": "You have two months to activate your Apple subscriptions."}, "30": {"title": "Your Apple Perks Expire This Month!", "time_modifier": "Don''t miss out on free music and TV! 📺"}}'),
('c2a1b459-e527-45c6-8321-59666524784e', 'Your chic, aesthetic getaway awaits! 💎 Use your credit at ''The Edit by Chase Travel'' for a stylish hotel stay.', '{"30": {"title": "Your Travel Credit Expires This Month!", "time_modifier": "There''s still a month to use your {{amount}} credit on a chic hotel. 🛎️"}, "14": {"title": "Time is Running Out on Your Travel Credit", "time_modifier": "Only two weeks left to claim your {{amount}} credit."}}'),
('c6004d5f-c5c4-435e-b717-eb6cafd9a089', 'It''s giving free trip energy! ✈️ Your anniversary miles are here. Start planning your next trip!', '{"60": {"title": "Time to Use Your Bonus Miles!", "time_modifier": "You have two months to use your 10,000 bonus miles. 🎉"}, "30": {"title": "Your Bonus Miles Expire This Month!", "time_modifier": "Don''t let your bonus miles disappear! Plan a trip this month."}}'),
('d538f219-3595-4a96-85da-508054a9b36d', 'Your table at that hot new spot is ready! 🍽️ Your Resy dining credit is expiring soon. Discover a new favorite restaurant!', '{"7": {"title": "Your Monthly Resy Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Resy credit."}, "3": {"title": "Don''t Forget Your Resy Credit!", "time_modifier": "Only 3 days left to dine out! 🥂"}, "1": {"title": "🚨 LAST DAY for your Resy Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('d8158b44-a979-40a5-ab13-1042577b5261', 'Adulting is hard, so treat yourself! 💅 Your Lifestyle Credit is here for food, rides, or streaming.', '{"60": {"title": "Time to Use Your Lifestyle Credit!", "time_modifier": "You have two months to use your {{amount}} lifestyle credit."}, "30": {"title": "Your Lifestyle Credit Expires This Month!", "time_modifier": "Don''t miss out on this life hack! Use your {{amount}} credit this month. 🛍️"}}'),
('d8158b44-a979-40a5-ab13-1042577b5263', 'Level up your flight! ✈️ Your Airline Fee Credit for things like checked bags or seat upgrades is expiring.', '{"14": {"title": "Planning a Trip Soon?", "time_modifier": "You have two weeks to use your {{amount}} airline fee credit."}, "7": {"title": "Your Airline Fee Credit Expires in a Week!", "time_modifier": "Don''t pay for extras! Be boujee on a budget. Use your {{amount}} credit. 💺"}}'),
('e1c07060-3c13-4387-be74-066ecc30b60f', 'Wanderlust loading... ✈️ Your Travel Credit is waiting to be used on flights, hotels, or more. Don''t let it fly away!', '{"60": {"title": "Time to Plan Your Next Adventure!", "time_modifier": "You have two months to use your {{amount}} travel credit. ☀️"}, "30": {"title": "Your Travel Credit Expires This Month!", "time_modifier": "Don''t miss out! Use your {{amount}} credit this month."}}'),
('ed2aa3a3-8ad3-4739-bf34-55eb1dd741c5', 'A second boba run, maybe? 🛒 Your second DoorDash credit for non-restaurant goodies is here for your snack emergencies!', '{"7": {"title": "Your Monthly DoorDash Perk is Expiring", "time_modifier": "You have one week left to use your second {{amount}} DoorDash credit."}, "3": {"title": "Don''t Forget Your DoorDash Credit!", "time_modifier": "Only 3 days left for a snack run! 🍪"}, "1": {"title": "🚨 LAST DAY for your DoorDash Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('f11e38e2-142b-425d-afa5-c06f86069218', 'Your ride is waiting! 🚕 Don''t let your monthly rideshare credit drive off without you. Where to?', '{"7": {"title": "Your Monthly Rideshare Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} rideshare credit."}, "3": {"title": "Don''t Forget Your Rideshare Credit!", "time_modifier": "Only 3 days left to get a lift! 🗺️"}, "1": {"title": "🚨 LAST DAY for your Rideshare Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('f79316d4-5ddd-4591-830b-6e897a3dd0f5', 'Time to roll! 🚗 Your Lyft credit is expiring. Tap to open the app and get to your next destination!', '{"7": {"title": "Your Monthly Lyft Perk is Expiring", "time_modifier": "You have one week left to use your {{amount}} Lyft credit."}, "3": {"title": "Don''t Forget Your Lyft Credit!", "time_modifier": "Only 3 days left to get a ride! 💨"}, "1": {"title": "🚨 LAST DAY for your Lyft Credit", "time_modifier": "Today is your final chance to use your {{amount}} credit!"}}'),
('ff646ff5-9d6e-4587-a44c-d6da0c219e0a', 'A free weekend getaway is calling your name! 🏨 Your Hilton Annual Free Night Reward is here. Book a spectacular stay!', '{"60": {"title": "Time to Plan Your Free Weekend!", "time_modifier": "You have two months to use your Hilton Free Night Reward. ✨"}, "30": {"title": "Your Free Night Reward Expires This Month!", "time_modifier": "Don''t miss out on a free weekend stay! Book it this month."}}'),
('ffc46725-85ed-47a8-8454-b4df2107020f', 'Zoom through the airport! ✈️ Your CLEAR Plus Credit from your Aspire card is about to expire. Keep the speedy travel perks going!', '{"60": {"title": "Time to Renew Your CLEAR Membership!", "time_modifier": "You have two months to use your {{amount}} CLEAR credit."}, "30": {"title": "Your CLEAR Credit Expires This Month!", "time_modifier": "Stay in the fast lane! Use your {{amount}} credit this month. 😎"}}');

