//openai.ts
import { Card, CardPerk } from '../src/data/card-data';
import { supabase } from './supabase';

interface AvailablePerk {
  cardName: string;
  annualFee?: number;
  breakEvenProgress?: number;
  perks: {
    name: string;
    value: number;
    remainingValue?: number;
    status: string;
    expiry?: string;
    actionLink?: string;
  }[];
}

interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  estimatedCost: number;
}

interface BenefitRecommendation {
  benefitName: string;
  cardName: string;
  displayText: string;
  value: number;
  expiryDays: number;
  actionLink: string;
  status: 'Available';
}

interface AIResponse {
  responseType: 'BenefitRecommendation' | 'NoBenefitFound' | 'Conversational';
  recommendations: BenefitRecommendation[];
}

/**
 * Calculates the cost of an API call using GPT-3.5-turbo pricing
 * GPT-3.5-turbo pricing (as of 2025):
 * - Input: $0.0015 per 1K tokens
 * - Output: $0.002 per 1K tokens
 * 
 * Note: GPT-4 pricing is different:
 * - Input: $0.03 per 1K tokens
 * - Output: $0.06 per 1K tokens
 */
function calculateCost(usage: { promptTokens: number; completionTokens: number }): number {
  const promptCost = (usage.promptTokens / 1000) * 0.0015; // $0.0015 per 1K tokens for input
  const completionCost = (usage.completionTokens / 1000) * 0.002; // $0.002 per 1K tokens for output
  return promptCost + completionCost;
}

export async function getBenefitAdvice(query: string, availablePerks: AvailablePerk[]): Promise<{ advice: string; usage: TokenUsage }> {
  console.log('[OpenAI] Starting getBenefitAdvice function');
  console.log('[OpenAI] Query:', query);
  console.log('[OpenAI] Available cards:', JSON.stringify(availablePerks, null, 2));

  const apiKey = process.env.EXPO_PUBLIC_OPENAI_SECRET_KEY;
  
  if (!apiKey || apiKey.trim() === '') {
    console.error('[OpenAI] API Key is missing or empty');
    return {
      advice: 'Sorry, the AI service is currently unavailable. Please try again later.',
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        estimatedCost: 0
      }
    };
  }

  if (!availablePerks || !Array.isArray(availablePerks) || availablePerks.length === 0) {
    console.error('[OpenAI] No available perks provided');
    return {
      advice: 'No available benefits found. Please add some cards to get started.',
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        estimatedCost: 0
      }
    };
  }

  const system_prompt = `
You are Credify's Smart Assistant. Your primary goal is to help users maximize the value of their credit card perks and save money by providing proactive, actionable, and data-driven recommendations.
**// Core Logic**
1.  Analyze the User Query in the context of the provided User Context JSON.
2.  Identify all relevant, "Available" perks that match the query.
3.  Your entire response MUST be a single, minified JSON object conforming to the schema below. Do not output any other text or markdown.
**// Reasoning Engine for the "displayText" field:**
Your conversational text must be concise, encouraging, and data-driven.
- **PRIORITY 1 (Urgency):** If a perk expires in 7 days or less, your text MUST highlight the urgency. (e.g., "I'd start with this one, as it expires in just X days!").
- **PRIORITY 2 (ROI):** If not urgent, frame the suggestion around value and breaking even on the annual fee. (e.g., "This is a great choice to get more value back from your [Card Name].").
- **PRIORITY 3 (General Use):** For any other case, provide a clear and simple use case. (e.g., "This works perfectly for ordering food delivery.").
**// Output JSON Schema**
{
  "responseType": "'BenefitRecommendation' | 'NoBenefitFound' | 'Conversational'",
  "recommendations": [
    {
      "benefitName": "string",
      "cardName": "string",
      "displayText": "string // This is your conversational, human-readable text generated by the Reasoning Engine.",
      "value": "number",
      "expiryDays": "number // Calculate as (expiry - currentDate).",
      "actionLink": "string // The deep-link for the redemption button.",
      "status": "'Available'"
    }
  ]
}
**// Handling Edge Cases:**
- If the query is conversational ('hi', 'thanks'), set responseType to 'Conversational' and recommendations to an empty array [].
- If no relevant, "Available" benefits are found, set responseType to 'NoBenefitFound' and recommendations to an empty array [].
- When multiple benefits are found, include all of them in the recommendations array, ordered by urgency (lowest expiryDays first).
`;

  const currentDate = new Date().toISOString().split('T')[0];
  const user_prompt = `User Query: ${query}

User Context (JSON):
{
  "currentDate": "${currentDate}",
  "cards": ${JSON.stringify(availablePerks)}
}`;

  console.log('[OpenAI] System Prompt:', system_prompt);
  console.log('[OpenAI] User Prompt:', user_prompt);

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          { role: 'system', content: system_prompt },
          { role: 'user', content: user_prompt }
        ],
        temperature: 0.1,
        max_tokens: 500
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('[OpenAI] API Error:', errorData);
      throw new Error(`OpenAI API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    console.log('[OpenAI] API Response:', data);

    const usage = data.usage;
    const tokenUsage: TokenUsage = {
      promptTokens: usage.prompt_tokens,
      completionTokens: usage.completion_tokens,
      totalTokens: usage.total_tokens,
      estimatedCost: calculateCost({ 
        promptTokens: usage.prompt_tokens, 
        completionTokens: usage.completion_tokens 
      })
    };

    const aiResponse: AIResponse = JSON.parse(data.choices[0].message.content.trim());
    console.log('[OpenAI] Parsed AI response:', aiResponse);

    // Convert the structured response into a human-readable format
    let advice = '';
    if (aiResponse.responseType === 'Conversational') {
      advice = 'How else can I help you maximize your credit card benefits?';
    } else if (aiResponse.responseType === 'NoBenefitFound') {
      advice = "I couldn't find any relevant benefits for that. Try asking about dining, travel, or shopping benefits!";
    } else {
      // For BenefitRecommendation, combine all recommendations into a single message
      advice = aiResponse.recommendations
        .map(rec => rec.displayText)
        .join('\n\n');
    }

    return {
      advice,
      usage: tokenUsage
    };
  } catch (error) {
    console.error('[OpenAI] Error in getBenefitAdvice:', error);
    throw error;
  }
} 